name: Build and Deploy Website and PDF
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    name: Compile and deploy Github Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: typst-community/setup-typst@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: uv sync --extra cpu

      - name: Build HTML
        env:
          BASE_URL: /${{ github.event.repository.name }}
        run: uv run jupyter book build --execute --html

      - name: Upload Output HTML as Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
